#!/usr/bin/env dart

import 'dart:convert';
import 'dart:io';

const _semverPattern =
    r'^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'
    r'(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?\+([1-9][0-9]*)$';

void main(List<String> args) {
  final options = _parseOptions(args);
  if (options.showHelp) {
    stdout.write(_usage);
    return;
  }
  if (options.error != null) {
    stderr.writeln(options.error);
    stderr.write(_usage);
    exit(2);
  }

  final root = Directory(options.rootPath).absolute;
  final failures = <String>[];
  final pubspecPath = _join(root.path, 'pubspec.yaml');
  final lockPath = _join(root.path, 'pubspec.lock');
  final pubspec = _readRequiredFile(pubspecPath, failures);
  final lockfile = _readRequiredFile(lockPath, failures);

  String? packageName;
  String? version;
  if (pubspec != null) {
    packageName = _topLevelScalar(pubspec, 'name', failures);
    version = _topLevelScalar(pubspec, 'version', failures);
    if (version != null && !_semver.hasMatch(version)) {
      failures.add(
        'pubspec.yaml version must be SemVer with a positive build number '
        '(for example, 1.2.3+4), got "$version".',
      );
    }
  }

  if (lockfile != null) {
    if (!lockfile.startsWith('# Generated by pub')) {
      failures.add('pubspec.lock is not a generated Pub lockfile.');
    }
    if (!lockfile.contains('\nsdks:\n')) {
      failures.add('pubspec.lock is missing its SDK constraint section.');
    }
    if (!RegExp(
      r'^  flutter:\s*"[^"\n]+"',
      multiLine: true,
    ).hasMatch(lockfile)) {
      failures.add('pubspec.lock is missing a pinned Flutter SDK constraint.');
    }
  }

  _requireTokens(root, 'android/app/build.gradle.kts', const [
    'versionCode = flutter.versionCode',
    'versionName = flutter.versionName',
  ], failures);
  _requireTokens(root, 'ios/Runner/Info.plist', const [
    r'$(FLUTTER_BUILD_NAME)',
    r'$(FLUTTER_BUILD_NUMBER)',
  ], failures);
  _requireTokens(root, 'macos/Runner/Info.plist', const [
    r'$(FLUTTER_BUILD_NAME)',
    r'$(FLUTTER_BUILD_NUMBER)',
  ], failures);
  if (options.requireReleaseSigning) {
    _checkReleaseSigning(root, failures);
  }
  if (options.requireAppleSigning) {
    _checkAppleSigning(root, failures);
  }
  if (options.requireProductionIdentifiers) {
    _checkProductionIdentifiers(root, failures);
  }

  if (options.requireClean) {
    _checkCleanGitTree(root, failures);
  }
  if (options.canonicalRef != null) {
    _checkCanonicalRef(root, options.canonicalRef!, failures);
  }

  if (failures.isNotEmpty) {
    stderr.writeln('release metadata preflight failed:');
    for (final failure in failures) {
      stderr.writeln('- $failure');
    }
    exit(1);
  }

  final versionParts = version!.split('+');
  final metadata = <String, Object>{
    'package': packageName!,
    'version': version,
    'buildName': versionParts.first,
    'buildNumber': int.parse(versionParts.last),
    'lockfile': 'pubspec.lock',
    'platformHandoff': const ['android', 'ios', 'macos'],
  };
  if (options.canonicalRef != null) {
    metadata['canonicalRef'] = options.canonicalRef!;
  }
  stdout.writeln(
    'release metadata preflight passed: '
    'RELEASE_METADATA_JSON=${jsonEncode(metadata)}',
  );
}

final _semver = RegExp(_semverPattern);

class _Options {
  const _Options({
    required this.rootPath,
    required this.requireClean,
    required this.requireReleaseSigning,
    required this.requireAppleSigning,
    required this.requireProductionIdentifiers,
    required this.canonicalRef,
    required this.showHelp,
    required this.error,
  });

  final String rootPath;
  final bool requireClean;
  final bool requireReleaseSigning;
  final bool requireAppleSigning;
  final bool requireProductionIdentifiers;
  final String? canonicalRef;
  final bool showHelp;
  final String? error;
}

_Options _parseOptions(List<String> args) {
  var rootPath = '.';
  var requireClean = false;
  var requireReleaseSigning = false;
  var requireAppleSigning = false;
  var requireProductionIdentifiers = false;
  String? canonicalRef;

  for (var index = 0; index < args.length; index++) {
    switch (args[index]) {
      case '--help':
      case '-h':
        return const _Options(
          rootPath: '.',
          requireClean: false,
          requireReleaseSigning: false,
          requireAppleSigning: false,
          requireProductionIdentifiers: false,
          canonicalRef: null,
          showHelp: true,
          error: null,
        );
      case '--require-clean':
        requireClean = true;
        break;
      case '--require-release-signing':
        requireReleaseSigning = true;
        break;
      case '--require-apple-signing':
        requireAppleSigning = true;
        break;
      case '--require-production-identifiers':
        requireProductionIdentifiers = true;
        break;
      case '--root':
        if (index + 1 >= args.length || args[index + 1].startsWith('-')) {
          return const _Options(
            rootPath: '.',
            requireClean: false,
            requireReleaseSigning: false,
            requireAppleSigning: false,
            requireProductionIdentifiers: false,
            canonicalRef: null,
            showHelp: false,
            error: '--root requires a directory path.',
          );
        }
        rootPath = args[++index];
        break;
      case '--canonical-ref':
        if (index + 1 >= args.length || args[index + 1].startsWith('-')) {
          return const _Options(
            rootPath: '.',
            requireClean: false,
            requireReleaseSigning: false,
            requireAppleSigning: false,
            requireProductionIdentifiers: false,
            canonicalRef: null,
            showHelp: false,
            error: '--canonical-ref requires a Git ref name.',
          );
        }
        canonicalRef = args[++index];
        break;
      default:
        return _Options(
          rootPath: rootPath,
          requireClean: requireClean,
          requireReleaseSigning: requireReleaseSigning,
          requireAppleSigning: requireAppleSigning,
          requireProductionIdentifiers: requireProductionIdentifiers,
          canonicalRef: canonicalRef,
          showHelp: false,
          error: 'Unknown argument: ${args[index]}',
        );
    }
  }

  return _Options(
    rootPath: rootPath,
    requireClean: requireClean,
    requireReleaseSigning: requireReleaseSigning,
    requireAppleSigning: requireAppleSigning,
    requireProductionIdentifiers: requireProductionIdentifiers,
    canonicalRef: canonicalRef,
    showHelp: false,
    error: null,
  );
}

String? _readRequiredFile(String path, List<String> failures) {
  final file = File(path);
  if (!file.existsSync()) {
    failures.add('Missing required file: ${_displayPath(path)}.');
    return null;
  }
  try {
    return file.readAsStringSync();
  } on FileSystemException catch (error) {
    failures.add('Unable to read ${_displayPath(path)}: $error');
    return null;
  }
}

String? _topLevelScalar(String contents, String key, List<String> failures) {
  final matches = <String>[];
  final pattern = RegExp(
    '^${RegExp.escape(key)}:\\s*(.*?)\\s*\$',
    multiLine: true,
  );
  for (final match in pattern.allMatches(contents)) {
    matches.add(_unquoteYamlScalar(match.group(1)!));
  }
  if (matches.length != 1 || matches.first.isEmpty) {
    failures.add(
      'pubspec.yaml must contain exactly one non-empty top-level $key field.',
    );
    return null;
  }
  return matches.first;
}

String _unquoteYamlScalar(String value) {
  if (value.length >= 2 &&
      ((value.startsWith("'") && value.endsWith("'")) ||
          (value.startsWith('"') && value.endsWith('"')))) {
    return value.substring(1, value.length - 1);
  }
  return value;
}

void _requireTokens(
  Directory root,
  String relativePath,
  List<String> tokens,
  List<String> failures,
) {
  final path = _join(root.path, relativePath);
  final contents = _readRequiredFile(path, failures);
  if (contents == null) {
    return;
  }
  for (final token in tokens) {
    if (!contents.contains(token)) {
      failures.add(
        '$relativePath is missing required version handoff "$token".',
      );
    }
  }
}

void _checkReleaseSigning(Directory root, List<String> failures) {
  const relativePath = 'android/app/build.gradle.kts';
  final contents = _readRequiredFile(_join(root.path, relativePath), failures);
  if (contents == null) {
    return;
  }

  final releaseBody = _extractBraceBlock(
    contents,
    RegExp(r'^\s*release\s*\{', multiLine: true),
  );
  if (releaseBody == null) {
    failures.add(
      '$relativePath is missing a parseable release build type block.',
    );
    return;
  }
  if (!RegExp(r'\bsigningConfig\s*=').hasMatch(releaseBody)) {
    failures.add(
      '$relativePath release build type must declare a signingConfig for '
      'production artifacts.',
    );
  }
  if (releaseBody.contains('TODO: Add your own signing config') ||
      RegExp(
        r'''signingConfigs(?:\.debug\b|\.getByName\s*\(\s*["']debug["']\s*\))''',
      ).hasMatch(releaseBody)) {
    failures.add(
      '$relativePath Android release build still uses debug signing; '
      'configure a release signing config before cutting a distributable '
      'artifact.',
    );
  }
}

String? _extractBraceBlock(String contents, RegExp headerPattern) {
  final header = headerPattern.firstMatch(contents);
  if (header == null) {
    return null;
  }
  final openingBrace = contents.indexOf('{', header.start);
  if (openingBrace < 0) {
    return null;
  }
  var depth = 0;
  for (var index = openingBrace; index < contents.length; index++) {
    final character = contents[index];
    if (character == '{') {
      depth++;
    } else if (character == '}') {
      depth--;
      if (depth == 0) {
        return contents.substring(openingBrace + 1, index);
      }
    }
  }
  return null;
}

void _checkAppleSigning(Directory root, List<String> failures) {
  _checkAppleSigningFile(
    root,
    'ios/Runner.xcodeproj/project.pbxproj',
    'iOS',
    failures,
  );
  _checkAppleSigningFile(
    root,
    'macos/Runner.xcodeproj/project.pbxproj',
    'macOS',
    failures,
  );
}

void _checkAppleSigningFile(
  Directory root,
  String relativePath,
  String platformLabel,
  List<String> failures,
) {
  final contents = _readRequiredFile(_join(root.path, relativePath), failures);
  if (contents == null) {
    return;
  }

  final releaseBlocks = _xcodeReleaseConfigurationBlocks(contents);
  if (releaseBlocks.isEmpty) {
    failures.add(
      '$relativePath has no parseable Release configuration for $platformLabel.',
    );
    return;
  }

  final hasUnsafeIdentity = releaseBlocks.any(
    (block) =>
        block.contains('CODE_SIGN_IDENTITY = "-"') ||
        block.contains('CODE_SIGN_IDENTITY = "iPhone Developer"') ||
        block.contains(
          '"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer"',
        ),
  );
  if (hasUnsafeIdentity) {
    failures.add(
      '$relativePath $platformLabel Release configuration uses a '
      'development or placeholder signing identity; configure Apple '
      'distribution signing before cutting a distributable artifact.',
    );
  }

  final hasTeam = releaseBlocks.any(
    (block) => RegExp(
      r'^\s*DEVELOPMENT_TEAM\s*=\s*[^;\s]+',
      multiLine: true,
    ).hasMatch(block),
  );
  final hasExplicitIdentity = releaseBlocks.any((block) {
    final identityLines = block
        .split('\n')
        .where((line) => line.contains('CODE_SIGN_IDENTITY'));
    return identityLines.any(
      (line) =>
          !line.contains(' = "-"') &&
          !line.contains('iPhone Developer') &&
          !line.contains(' = ""'),
    );
  });
  if (!hasTeam && !hasExplicitIdentity) {
    failures.add(
      '$relativePath $platformLabel Release configuration must declare '
      'DEVELOPMENT_TEAM or a distribution CODE_SIGN_IDENTITY.',
    );
  }
}

List<String> _xcodeReleaseConfigurationBlocks(String contents) {
  return RegExp(
    r'[A-F0-9]+ /\* Release \*/ = \{.*?name = Release;',
    dotAll: true,
  ).allMatches(contents).map((match) => match.group(0)!).toList();
}

void _checkProductionIdentifiers(Directory root, List<String> failures) {
  _checkAndroidProductionIdentifier(root, failures);
  _checkAppleProductionIdentifier(
    root,
    'ios/Runner.xcodeproj/project.pbxproj',
    'iOS',
    failures,
  );
  _checkAppleProductionIdentifier(
    root,
    'macos/Runner.xcodeproj/project.pbxproj',
    'macOS',
    failures,
    supplementalPaths: const ['macos/Runner/Configs/AppInfo.xcconfig'],
  );
}

void _checkAndroidProductionIdentifier(Directory root, List<String> failures) {
  const relativePath = 'android/app/build.gradle.kts';
  final contents = _readRequiredFile(_join(root.path, relativePath), failures);
  if (contents == null) {
    return;
  }
  final match = RegExp(
    r'''^\s*applicationId\s*=\s*["']([^"']+)["']''',
    multiLine: true,
  ).firstMatch(contents);
  if (match == null) {
    failures.add(
      '$relativePath must declare a concrete applicationId for production '
      'artifacts.',
    );
    return;
  }
  final identifier = match.group(1)!;
  if (_isTemplateIdentifier(identifier)) {
    failures.add(
      '$relativePath applicationId "$identifier" is a template or '
      'unresolved value; replace it with the production Android identifier.',
    );
  }
}

void _checkAppleProductionIdentifier(
  Directory root,
  String relativePath,
  String platformLabel,
  List<String> failures, {
  List<String> supplementalPaths = const [],
}) {
  final contents = _readRequiredFile(_join(root.path, relativePath), failures);
  if (contents == null) {
    return;
  }
  final releaseBlocks = _xcodeReleaseConfigurationBlocks(contents);
  if (releaseBlocks.isEmpty) {
    failures.add(
      '$relativePath has no parseable Release configuration for $platformLabel.',
    );
    return;
  }

  final identifierLines = <String>[];
  for (final block in releaseBlocks) {
    identifierLines.addAll(
      block
          .split('\n')
          .where((line) => line.contains('PRODUCT_BUNDLE_IDENTIFIER')),
    );
  }
  for (final supplementalPath in supplementalPaths) {
    final supplemental = _readRequiredFile(
      _join(root.path, supplementalPath),
      failures,
    );
    if (supplemental != null) {
      identifierLines.addAll(
        supplemental
            .split('\n')
            .where((line) => line.contains('PRODUCT_BUNDLE_IDENTIFIER')),
      );
    }
  }
  if (identifierLines.isEmpty) {
    failures.add(
      '$relativePath $platformLabel Release configuration must declare a '
      'concrete PRODUCT_BUNDLE_IDENTIFIER.',
    );
    return;
  }

  final identifierPattern = RegExp(
    r'''PRODUCT_BUNDLE_IDENTIFIER\s*=\s*["']?([^;"'\s]+)''',
  );
  var appIdentifierCount = 0;
  for (final line in identifierLines) {
    final match = identifierPattern.firstMatch(line);
    final identifier = match?.group(1);
    if (identifier != null && identifier.endsWith('.RunnerTests')) {
      continue;
    }
    appIdentifierCount++;
    if (identifier == null || _isTemplateIdentifier(identifier)) {
      final displayIdentifier = identifier ?? line.trim();
      failures.add(
        '$relativePath $platformLabel Release bundle identifier '
        '"$displayIdentifier" is a template or unresolved value; replace it '
        'with the production Apple identifier.',
      );
    }
  }
  if (appIdentifierCount == 0) {
    failures.add(
      '$relativePath $platformLabel Release configuration must declare a '
      'concrete application PRODUCT_BUNDLE_IDENTIFIER.',
    );
  }
}

bool _isTemplateIdentifier(String identifier) {
  final normalized = identifier.toLowerCase();
  return normalized.contains('com.example') ||
      normalized.contains('example.com') ||
      normalized.contains('your_') ||
      normalized.contains('change_me') ||
      identifier.startsWith(r'$(');
}

void _checkCleanGitTree(Directory root, List<String> failures) {
  final result = Process.runSync('git', [
    '-C',
    root.path,
    'status',
    '--porcelain',
    '--untracked-files=all',
  ]);
  if (result.exitCode != 0) {
    failures.add(
      'Unable to inspect Git status for clean release preflight: '
      '${result.stderr.toString().trim()}',
    );
    return;
  }
  if (result.stdout.toString().trim().isNotEmpty) {
    failures.add(
      'Git worktree is not clean; commit or stash changes before a release.',
    );
  }
}

void _checkCanonicalRef(
  Directory root,
  String canonicalRef,
  List<String> failures,
) {
  final headResult = Process.runSync('git', [
    '-C',
    root.path,
    'rev-parse',
    '--verify',
    'HEAD',
  ]);
  final refResult = Process.runSync('git', [
    '-C',
    root.path,
    'rev-parse',
    '--verify',
    '$canonicalRef^{commit}',
  ]);
  if (headResult.exitCode != 0 || refResult.exitCode != 0) {
    failures.add('Canonical Git ref "$canonicalRef" could not be resolved.');
    return;
  }
  final head = headResult.stdout.toString().trim();
  final ref = refResult.stdout.toString().trim();
  if (head != ref) {
    failures.add(
      'HEAD $head does not match canonical ref "$canonicalRef" ($ref).',
    );
  }
}

String _join(String root, String relative) {
  return '$root${Platform.pathSeparator}$relative';
}

String _displayPath(String path) {
  final current = Directory.current.absolute.path;
  if (path.startsWith('$current${Platform.pathSeparator}')) {
    return path.substring(current.length + 1);
  }
  return path;
}

const _usage = '''Usage: dart tool/check_release_metadata.dart [options]

Validates the canonical package version, locked dependencies, and native
platform version handoff used by release builds.

Options:
  --root <path>             Validate a different project root (default: .).
  --require-clean           Require a clean Git worktree.
  --require-release-signing Require a non-debug Android release signing config.
  --require-apple-signing   Require iOS/macOS distribution signing metadata.
  --require-production-     Require concrete non-template Android/iOS/macOS
    identifiers             bundle/application identifiers.
  --canonical-ref <ref>     Require HEAD to equal this Git ref.
  -h, --help                Show this help.
''';
